"""initial: universal types

Revision ID: 7f0cffb73e82
Revises: 
Create Date: 2026-06-24 20:18:32.308166
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7f0cffb73e82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('strategy', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'REVIEWED', 'DISMISSED', 'ESCALATED', name='clusterstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clusters_created_at', 'clusters', ['created_at'], unique=False)
    op.create_index('ix_clusters_status', 'clusters', ['status'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('WAZUH', 'ELASTIC', 'GRAYLOG', 'SPLUNK', 'WEBHOOK', name='sourcetype'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ERROR', 'DISABLED', name='sourcestatus'), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sources_type_status', 'sources', ['type', 'status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='usertier'), nullable=False),
    sa.Column('alert_limit_daily', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('rule_id', sa.String(length=128), nullable=False),
    sa.Column('rule_name', sa.String(length=512), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('source_hostname', sa.String(length=255), nullable=True),
    sa.Column('destination_ip', sa.String(length=45), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('full_log', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CLUSTERED', 'DISMISSED', 'ESCALATED', name='alertstatus'), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('normalized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_agent_name', 'alerts', ['agent_name'], unique=False)
    op.create_index('ix_alerts_cluster_id', 'alerts', ['cluster_id'], unique=False)
    op.create_index('ix_alerts_received_at', 'alerts', ['received_at'], unique=False)
    op.create_index('ix_alerts_rule_id', 'alerts', ['rule_id'], unique=False)
    op.create_index('ix_alerts_severity_received', 'alerts', ['severity', 'received_at'], unique=False)
    op.create_index('ix_alerts_source_external', 'alerts', ['source_id', 'external_id'], unique=True)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_table('rule_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('external_rule_id', sa.String(length=128), nullable=False),
    sa.Column('rule_name', sa.String(length=512), nullable=True),
    sa.Column('noise_score', sa.Float(), nullable=False),
    sa.Column('times_clustered', sa.Integer(), nullable=False),
    sa.Column('times_escalated', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_rule_id', name='uq_rule_stats_source_rule')
    )
    op.create_index('ix_rule_stats_noise_score', 'rule_stats', ['noise_score'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('cluster_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.Enum('CONFIRMED_NOISE', 'CONFIRMED_INCIDENT', 'UNGROUPED', name='decision'), nullable=False),
    sa.Column('source', sa.Enum('EXPLICIT', 'IMPLICIT', name='feedbacksource'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_alert_id', 'feedback', ['alert_id'], unique=False)
    op.create_index('ix_feedback_cluster_id', 'feedback', ['cluster_id'], unique=False)
    op.create_index('ix_feedback_created_at', 'feedback', ['created_at'], unique=False)
    op.create_index('ix_feedback_user_id', 'feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_user_id', table_name='feedback')
    op.drop_index('ix_feedback_created_at', table_name='feedback')
    op.drop_index('ix_feedback_cluster_id', table_name='feedback')
    op.drop_index('ix_feedback_alert_id', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_rule_stats_noise_score', table_name='rule_stats')
    op.drop_table('rule_stats')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_source_external', table_name='alerts')
    op.drop_index('ix_alerts_severity_received', table_name='alerts')
    op.drop_index('ix_alerts_rule_id', table_name='alerts')
    op.drop_index('ix_alerts_received_at', table_name='alerts')
    op.drop_index('ix_alerts_cluster_id', table_name='alerts')
    op.drop_index('ix_alerts_agent_name', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('users')
    op.drop_index('ix_sources_type_status', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_clusters_status', table_name='clusters')
    op.drop_index('ix_clusters_created_at', table_name='clusters')
    op.drop_table('clusters')
    # ### end Alembic commands ###
